### ISSUE TITLE
The how-to-filter help is taking a lot of space in the box

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/dataportal-explorer#47]
Please, remove the Help text from the box and put it as pop-up box when mouse over in order to release some space in the menu-box and make it shorter

![exp help](https://cloud.githubusercontent.com/assets/3705866/7507062/52036054-f42f-11e4-94e4-5d200004e6bd.PNG)

**Comment by danipilze** [comment]
thanks for doing this
please cite the changes that made this possible

**Comment by valegrajales** [comment]
Fixed in 3523dc7926fa107ade3ba1bc1c22f4d4fb8b9518
