### ISSUE TITLE
Change downloads citation file

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/dataportal-explorer#49]
please, change it to follow this sample format:

> Conjunto de datos: Herbario Amazónico Colombiano

> Por favor citar estos datos de la siguiente manera:
> Instituto Amazónico de Investigaciones Científicas - SINCHI (2012 - ). Herbario Amazónico Colombiano, 56155 Registros, Aportados por Cardenas, D., Sua S., Mantilla-Cárdenas LM (Contacto del Recurso, Creador del Recurso, publicador), En línea, http://ipt.sibcolombia.net/sinchi/, Versión 1.0 (actualizado por última vez el 19/12/2012).

**Comment by valegrajales** [comment]
Fixed in ae8bbe1d2f623516ba40e5501e8502be640b1e1b
