### ISSUE TITLE
Change downloads rights file

### ISSUE THREAD

**Issue by danipilze** [SIB-Colombia/dataportal-explorer#50]
Please change the name of the file from "rights.txt" to "license.txt"

And please change the format to the following:

> Conjunto de datos: Herbario Amazónico Colombiano, http://data.sibcolombia.net/datasets/resource/47
> Licencia de uso: Este conjunto de datos posee una licencia de uso Creative Commons CCZero 1.0 License http://creativecommons.org/publicdomain/zero/1.0/legalcode

**Comment by valegrajales** [comment]
Fixed in ae8bbe1d2f623516ba40e5501e8502be640b1e1b
