### ISSUE TITLE
Cell distribution-zoom

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/dataportal-explorer#69]
Is better for the  visualization if the distribution cell size reduced automatically based in zoom selection, because it generate an overestimation of the results if the user doesn’t reduce the cell size. Additionally  the cluster of the registries can be displayed at less zoom

**Comment by danipilze** [comment]
@valegrajales please solve this by always showing the best resolution of the search

**Comment by danipilze** [comment]
sorry, it will marked as wontfix due to #74

**Comment by danipilze** [comment]
issue #74 will not be fixed right now 
please fix this
